/**
 * E11 — database client + migrations (RPE-88)
 *
 * One entry point, two dialects:
 *   - DATABASE_URL = postgres://…  → node-postgres Pool (staging/prod)
 *   - DATABASE_URL = file:…/:memory:/*.db → better-sqlite3 (local/test)
 *
 * Checked-in migrations live in migrations/pg and migrations/sqlite
 * (generated by `pnpm --filter @rpe/db db:generate`); applyMigrations()
 * runs the folder matching the live dialect — CI and deploy call the
 * same function.
 *
 * DATABASE_URL is env-only; nothing is committed (RPE-82 wires the
 * staging secret).
 */

import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';
import { drizzle as drizzlePg, type NodePgDatabase } from 'drizzle-orm/node-postgres';
import { drizzle as drizzleSqlite, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { migrate as migratePg } from 'drizzle-orm/node-postgres/migrator';
import { migrate as migrateSqlite } from 'drizzle-orm/better-sqlite3/migrator';
import pg from 'pg';
import { pgSchema } from './schema.pg.js';
import { sqliteSchema } from './schema.sqlite.js';

const MIGRATIONS_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '../migrations');

export type Dialect = 'postgres' | 'sqlite';

interface RpeDbBase {
  /** Apply the checked-in migrations for the live dialect. */
  applyMigrations: () => Promise<void>;
  close: () => Promise<void>;
}

/** Discriminated on `dialect` — narrowing gives the typed Drizzle instance. */
export type RpeDb =
  | (RpeDbBase & { dialect: 'postgres'; pg: NodePgDatabase<typeof pgSchema> })
  | (RpeDbBase & { dialect: 'sqlite'; sqlite: BetterSQLite3Database<typeof sqliteSchema> });

export function resolveDialect(url: string): Dialect {
  if (/^postgres(ql)?:\/\//i.test(url)) return 'postgres';
  if (url === ':memory:' || url.startsWith('file:') || url.endsWith('.db') || url.endsWith('.sqlite')) {
    return 'sqlite';
  }
  throw new Error(
    `Unrecognized DATABASE_URL — expected postgres://…, file:…, :memory:, or a .db/.sqlite path`,
  );
}

/** Create a client for the given DSN (defaults to env DATABASE_URL). */
export function createDb(url: string | undefined = process.env['DATABASE_URL']): RpeDb {
  if (url === undefined || url.trim() === '') {
    throw new Error('DATABASE_URL is required (postgres://… or a SQLite path/:memory:)');
  }

  const dialect = resolveDialect(url);

  if (dialect === 'postgres') {
    const pool = new pg.Pool({ connectionString: url });
    const db = drizzlePg(pool, { schema: pgSchema });
    return {
      dialect,
      pg: db,
      applyMigrations: async () => {
        await migratePg(db, { migrationsFolder: `${MIGRATIONS_DIR}/pg` });
      },
      close: () => pool.end(),
    };
  }

  const sqlitePath = url.startsWith('file:') ? url.slice('file:'.length) : url;
  const sqlite = new Database(sqlitePath);
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  const db = drizzleSqlite(sqlite, { schema: sqliteSchema });
  return {
    dialect,
    sqlite: db,
    applyMigrations: async () => {
      migrateSqlite(db, { migrationsFolder: `${MIGRATIONS_DIR}/sqlite` });
    },
    close: async () => {
      sqlite.close();
    },
  };
}
