/**
 * E11 — database client + migrations (RPE-88)
 *
 * One entry point, two dialects:
 *   - DATABASE_URL = postgres://…  → node-postgres Pool (staging/prod)
 *   - DATABASE_URL = file:…/:memory:/*.db → better-sqlite3 (local/test)
 *
 * Checked-in migrations live in migrations/pg and migrations/sqlite
 * (generated by `pnpm --filter @rpe/db db:generate`); applyMigrations()
 * runs the folder matching the live dialect — CI and deploy call the
 * same function.
 *
 * DATABASE_URL is env-only; nothing is committed (RPE-82 wires the
 * staging secret).
 */

import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';
import { drizzle as drizzlePg, type NodePgDatabase } from 'drizzle-orm/node-postgres';
import { drizzle as drizzleSqlite, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { migrate as migratePg } from 'drizzle-orm/node-postgres/migrator';
import { migrate as migrateSqlite } from 'drizzle-orm/better-sqlite3/migrator';
import pg from 'pg';
import { pgSchema } from './schema.pg.js';
import { sqliteSchema } from './schema.sqlite.js';

/**
 * Locate the checked-in migrations. The source-relative path breaks
 * when this module is BUNDLED (import.meta.url then points inside the
 * consumer's dist), so candidates are tried in order:
 *   1. RPE_MIGRATIONS_DIR (deploys point at the shipped folder)
 *   2. next to the executing bundle (dist/migrations)
 *   3. source-relative (monorepo dev/test)
 *   4. workspace-relative from cwd (bundled api run from apps/api)
 */
function migrationsDir(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    process.env['RPE_MIGRATIONS_DIR'],
    resolve(here, 'migrations'),
    resolve(here, '../migrations'),
    resolve(process.cwd(), '../../packages/db/migrations'),
    resolve(process.cwd(), 'packages/db/migrations'),
  ].filter((c): c is string => c !== undefined && c !== '');
  const found = candidates.find((c) => existsSync(c));
  if (found === undefined) {
    throw new Error(
      `@rpe/db: migrations folder not found — set RPE_MIGRATIONS_DIR. Tried: ${candidates.join(', ')}`,
    );
  }
  return found;
}

const MIGRATIONS_DIR = migrationsDir();

export type Dialect = 'postgres' | 'sqlite';

interface RpeDbBase {
  /** Apply the checked-in migrations for the live dialect. */
  applyMigrations: () => Promise<void>;
  close: () => Promise<void>;
}

/** Discriminated on `dialect` — narrowing gives the typed Drizzle instance. */
export type RpeDb =
  | (RpeDbBase & { dialect: 'postgres'; pg: NodePgDatabase<typeof pgSchema> })
  | (RpeDbBase & { dialect: 'sqlite'; sqlite: BetterSQLite3Database<typeof sqliteSchema> });

export function resolveDialect(url: string): Dialect {
  if (/^postgres(ql)?:\/\//i.test(url)) return 'postgres';
  if (url === ':memory:' || url.startsWith('file:') || url.endsWith('.db') || url.endsWith('.sqlite')) {
    return 'sqlite';
  }
  throw new Error(
    `Unrecognized DATABASE_URL — expected postgres://…, file:…, :memory:, or a .db/.sqlite path`,
  );
}

/** Create a client for the given DSN (defaults to env DATABASE_URL). */
export function createDb(url: string | undefined = process.env['DATABASE_URL']): RpeDb {
  if (url === undefined || url.trim() === '') {
    throw new Error('DATABASE_URL is required (postgres://… or a SQLite path/:memory:)');
  }

  const dialect = resolveDialect(url);

  if (dialect === 'postgres') {
    const pool = new pg.Pool({ connectionString: url });
    const db = drizzlePg(pool, { schema: pgSchema });
    return {
      dialect,
      pg: db,
      applyMigrations: async () => {
        await migratePg(db, { migrationsFolder: `${MIGRATIONS_DIR}/pg` });
      },
      close: () => pool.end(),
    };
  }

  const sqlitePath = url.startsWith('file:') ? url.slice('file:'.length) : url;
  const sqlite = new Database(sqlitePath);
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  const db = drizzleSqlite(sqlite, { schema: sqliteSchema });
  return {
    dialect,
    sqlite: db,
    applyMigrations: async () => {
      migrateSqlite(db, { migrationsFolder: `${MIGRATIONS_DIR}/sqlite` });
    },
    close: async () => {
      sqlite.close();
    },
  };
}
